spring:
  application:
    name: learn-graphql-java

#server:
#  http2:
#    enabled:true

graphql:
  servlet:
    max-query-depth: 5

  playground:
    headers:
      Authorization: Bearer Token
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
    enabled: true

voyager:
  cdn:
    enabled: true
  enabled: true
